## NUMPY ARRAY AND BASICS 

In [2]:
import numpy as np 

creating array from list

In [6]:
arr_1d=np.array([1,2,3,4,5])
print("1D Array :",arr_1d)

arr_2d=np.array([1,2,3],[4,5,6])
print("2D Array : ",arr_2d)

1D Array : [1 2 3 4 5]


TypeError: Field elements must be 2- or 3-tuples, got '4'

list VS Numpy

In [9]:
list=[1,2,3]
print("list * 2 :", list*2)

np_array=np.array([1,2,3]) #elements wise multilicaton
print("Array *2  :",np_array*2)

import time
start=time.time()
list=[i*2 for i in range(10000)]
print("\n List operation time : ", time.time() - start)

start=time.time()
np_array=np.arange(10000) * 2
print("\n Numpy operation time : ", time.time() - start)

list * 2 : [1, 2, 3, 1, 2, 3]
Array *2  : [2 4 6]

 List operation time :  0.0010027885437011719

 Numpy operation time :  0.0019986629486083984


creating new new array

In [ ]:
zero=np.zeros((3,4)) #row , colum 
print("Zero matrix: \n",zero)


one=np.ones((3,4)) #row , colum 
print("One matrix: \n",one)

#Full methords
full=np.full((3,4),7 ) #((row , colum ), element want to fill the matrix)
print("full matrix: \n",full)

#Random Methods
random=np.random.random((3,4)) *100
print("random matrix: \n",random)


#secequenc array
seq=np.arange(1,10,2) #start , end , step
print("Sequence array: \n",seq)

Zero matrix: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
One matrix: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full matrix: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random matrix: 
 [[63.00009472 15.31513494 10.007567   59.82800705]
 [91.38798208  8.94381906 25.20904139  7.57370308]
 [69.29051363 73.32063496  8.11822743 69.35165167]]
Sequence array: 
 [1 3 5 7 9]


## Vector , Matrix and Tensor

In [7]:

vector=np.array([1,2,3])
print("Vector: \n",vector)

#Matrix is a 2D array
#Here we create a 2D matrix with shape (2, 3)
matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Matrix: \n",matrix)

#Tensor is a multi-dimensional array
#Here we create a 3D tensor with shape (2, 2, 2)
tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor: \n",tensor)

Vector: 
 [1 2 3]
Matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties


In [10]:
arr= np.array([[1,2,3],
               [4,5,6]])
print("shape : ",arr.shape)
print("dimention : ",arr.ndim)
print("data type : ",arr.dtype)
print("size : ",arr.size)

shape :  (2, 3)
dimention :  2
data type :  int64
size :  6


## Array Reshape


In [19]:
arr= np.arange(12)
print("Original array: ",arr)

#reshaped the array 
reshape= arr.reshape((3,4))
print("\n Reshaped Array: \n", reshape)
print("\n Reshaped Array shape: \n",reshape.shape)

#flattend array   ...return the copy
flattened=reshape.flatten()
print("\n flattend Array: ",flattened)

#it returns view instead of copy ......return original array
raveled=reshape.ravel()
print("\n raveled Array: ",raveled)

#Transpose
transpose=reshape.T
print("\ntranspose Array: \n",transpose)
print("\ntranspose Array shape: \n",transpose.shape)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Reshaped Array shape: 
 (3, 4)

 flattend Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

transpose Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

transpose Array shape: 
 (4, 3)
