## Numpy Array Operations

In [1]:
import numpy as np 

## Slicing

In [2]:
#slicing
arr= np.arange(12)

print("Basic slicing: ",arr[2:7])

Basic slicing:  [2 3 4 5 6]


In [3]:
#2d array 

arr2= np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("specific element: ",arr2[1,2])
print("specific element: ",arr2[0,0])
print("specific element: ",arr2[2])#row 
print("specific element: ",arr2[:,2])#column

specific element:  6
specific element:  1
specific element:  [7 8 9]
specific element:  [3 6 9]


## Sorting

In [4]:
unsorted= np.array([3,5,6,23,2,5,6,8,1,3,456,56,6])
print("\n Sorted Array shape: \n",np.sort(unsorted))

arr2d=np.array([[3,1],[3,2],[2,1]])
print("Shored by 2D array by column: \n",np.sort(arr2d,axis=0))
print("Shored by 2D array by row : \n",np.sort(arr2d,axis=1))


 Sorted Array shape: 
 [  1   2   3   3   5   5   6   6   6   8  23  56 456]
Shored by 2D array by column: 
 [[2 1]
 [3 1]
 [3 2]]
Shored by 2D array by row : 
 [[1 3]
 [2 3]
 [1 2]]


## Flitering

In [5]:
numbers=np.arange(12)
even_num=numbers[numbers%2==0] #mask 
print("Even numbers: ",even_num)

Even numbers:  [ 0  2  4  6  8 10]


## filter with mask

In [6]:
mask= numbers>5 #expretion
print("numbers >5 :",numbers[mask]) #hold evalution's evalutons  

numbers >5 : [ 6  7  8  9 10 11]


## fancy indexing vs np.where

In [7]:
indices=[0,2,3] 
print(numbers[indices])#array position value ..

where_result= np.where(numbers>5)
print(numbers[where_result])
print(where_result)

[0 2 3]
[ 6  7  8  9 10 11]
(array([ 6,  7,  8,  9, 10, 11]),)


In [8]:
condition_arr= np.where(numbers>5,"true", "false")
# if(numbers>5){
#     True
# }
# else{
# False  }


print(condition_arr)

['false' 'false' 'false' 'false' 'false' 'false' 'true' 'true' 'true'
 'true' 'true' 'true']


## Adding and removind datas


In [ ]:
arr1=np.array([2,4,5])
arr2=np.array([3,6,7])
combined=np.concatenate((arr2,arr1)) #add

print(arr1+arr2)
print(combined)


[ 5 10 12]
[3 6 7 2 4 5]


## Array comatibility

In [15]:
arr1=np.array([2,4,5])
arr2=np.array([3,6,7])
arr3=np.array([3,6,7,3,4,5])



print("comatibility check: ", arr1.shape==arr2.shape)
print("comatibility check: ", arr1.shape==arr3.shape)


comatibility check:  True
comatibility check:  False


In [ ]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,7]])
with_new_row=np.vstack((original,new_row)) #vstack  adds row
print(with_new_row)

new_col=np.array([[7],[9]])
with_new_col=np.hstack((original,new_col)) #hstack adds column
print("\n",with_new_col)

[[1 2]
 [3 4]
 [5 7]]

 [[1 2 7]
 [3 4 9]]


In [ ]:
#Deleting

arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2) #delet the position as mention ....retune the array after deletion.!!

print("\n",deleted)


 [1 2 4 5]
